### ISSUE TITLE
slc pmctl does not find service

### ISSUE THREAD

**Issue by grosem** [strongloop/strong-pm#158]
Hi,

executing 'slc pmctl' does not return on an Ubuntu Server.

:/var/lib/strong-pm# slc -v
strongloop v3.0.4 (node v0.12.0)
├── strong-arc@1.1.0
├── strong-build@1.0.3 (5a43a57)
├── strong-deploy@1.1.5 (c8f39ec)
├── strong-pm@3.1.0 (89bf840)
├── strong-registry@1.1.4 (aab3dbb)
├── strong-start@1.0.2 (fa68a7f)
├─┬ strong-supervisor@1.4.1 (c945bd1)
│ └── strong-agent@1.3.2
├── generator-loopback@1.9.0 (b90e9cd)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

status strong-pm  returns:
strong-pm start/running, process 855

Also, in the github docs of slc pmctl is a duplicate:

3. `/var/lib/strong-pm/pmctl`: a process manager installed by pm-install.
4. `/var/lib/strong-pm/pmctl`: a process manager installed by pm-install.

**Comment by sam-github** [comment]
The docs were out of sync with the CLI, `slc pmctl -h` gives correct docs.

I think you have a new pmctl and an older version of strong-pm. strong-pm 3.x changed the protocol, possible?

If so, you'll need to update your server. Please look at the bottom of this page:

http://docs.strongloop.com/display/SLC/Setting+up+a+production+host

for the header "Upgrading Process Manager"

**Comment by grosem** [comment]
You were right. Unfortunately I cannot update because of
https://github.com/strongloop/strong-mesh-models/issues/31

Sam Roberts <notifications@github.com> schrieb am Mi., 18. März 2015 um
17:28 Uhr:

**Comment by rmg** [comment]
@grosem that should be fixed now, please try again.

**Comment by grosem** [comment]
@sam-github I updated strong-pm to 3.1.3 and followed the docs you mentioned. However, pmctl still cannot get a status from the running process.

That's what I see in the logs: http://pastebin.com/thd3T693

**Comment by rmg** [comment]
@grosem can you include the output of `DEBUG=* slc ctl`? And while you're at it, the output of `ls -l /var/lib/strong-pm/pmctl` might also be helpful.

**Comment by grosem** [comment]
Sure:

ls -l /var/lib/strong-pm/pmctl
srwxr-xr-x 1 strong-pm strong-pm 0 Mar 19 17:24 /var/lib/strong-pm/pmctl

DEBUG=* slc ctl http://pastebin.com/WfQCtzyD





2015-03-19 17:25 GMT+01:00 Ryan Graham <notifications@github.com>:

**Comment by rmg** [comment]
@kraman you're most familiar with this now, I think. Does the debug output tell you anything?

**Comment by grosem** [comment]
I just noticed that this line was added after I copied the code:

Command status failed with Error: read ECONNRESET

according to `status strong-pm` it is still runing though.

2015-03-19 17:54 GMT+01:00 Ryan Graham <notifications@github.com>:

**Comment by sam-github** [comment]
```
  loopback:boot:compiler Found model "Service" - ../common/models/service.json ../common/models/service.js +1ms
  loopback:boot:compiler Model source code not found: undefined - TypeError: Arguments to path.join must be strings +1ms
```

**Comment by grosem** [comment]
When no application is deployed it returns me a status

`sl-pmctl status`
manager:
  pid:                1250
  port:               8701
  base:               /var/lib/strong-pm/.strong-pm
current:              (none)


@sam-github how can I track down the source of this TypeError?

**Comment by kraman** [comment]
@sam-github that warning is normal I think. Perhaps Miro will have a better idea.

**Comment by kraman** [comment]
@grosem. Have you deployed anything on the pm instance?

Can you run a process listing on you pm server machine and paste the node processes here please

**Comment by grosem** [comment]
Alright, I noticed this:

If I always deploy via slc in the terminal there is no problem at all - everything works just fine.
As soon as I deploy via arc it's somehow screwed up. Even deploying via terminal does not work anymore. Perhaps you have an idea why this could make a difference (all packages were up-to-date as of yesterday). Both times I used deploy as package, not via git.

I'm fine with using the terminal for deploying my app - if nobody else is facing this problem I don't mind closing this incident. 

@kraman: If you are still interested in the information you asked for, just let me know - happy to help.

**Comment by sam-github** [comment]
If you can do it with the CLI you should be able to do it with arc, so something is definitely broken. Thanks for you patience, and yes, we'd still like that info.

**Comment by grosem** [comment]
There you go:

strong-+   855  5.3 80.1 3324080 816104 ?      Rsl  19:31  10:28 /usr/local/bin/node /usr/local/lib/node_modules/strong-pm/bin/sl-pm.js --listen 8701 --base /var/lib/strong-pm/.strong-pm
strong-+  3890  0.0  0.0 1037732   48 ?        Sl   19:35   0:08 /usr/local/bin/node /usr/local/lib/node_modules/strong-pm/node_modules/strong-supervisor/bin/sl-run.js --cluster=CPU
strong-+  3891  0.0  0.0 957128     4 ?        Sl   19:35   0:03 /usr/local/bin/node --debug-port=5859 /usr/local/lib/node_modules/strong-pm/node_modules/strong-supervisor/bin/sl-run.js .
